export type Status = 'not_started'|'learning'|'mastered'
export type Topic = { id:string; name:string; description:string; subtopics:string[] }
export type Chapter = { id:string; name:string; topics:Topic[] }
export type Subject = { id:string; name:string; stream?:string; chapters:Chapter[] }
export type SchoolClass = { id:string; name:string; level:string; blurb:string; subjects:Subject[] }
export type Scene = { title:string; text:string; emoji:string }
export type Level = 'Easy'|'Medium'|'Hard'
export type Question = { type:'MCQ'|'True/False'|'Application'; q:string; options:string[]; answer:number; concept:string; level?:Level; hint?:string; why?:string }
export type TopicContent = { storyTitle:string; scenes:Scene[]; questions:Question[]; strong:string[]; weak:string[]; reteach?:{concept:string;card:string;visual?:string;q:string;options:string[];answer:number} }
export type QuizResult = { score:number; total:number; correct:string[]; missed:string[] }
export type PracticeBest = Partial<Record<Level,number>>
