// Generates supabase/seed.sql from src/data/curriculum.ts (needs Node 22.6+).  npm run seed:sql
import { writeFileSync } from 'node:fs'
import { curriculum, topicContent } from '../src/data/curriculum.ts'
const q=(v:unknown)=>`'${String(v).replace(/'/g,"''")}'`
const out:string[]=['-- Generated by scripts/gen-seed.ts. Safe to re-run.','begin;']
out.push(`delete from classes where id not in (${curriculum.map(c=>q(c.id)).join(',')});`) // removes classes dropped from the curriculum (cascades to their subjects, chapters, topics and content)
curriculum.forEach((c,ci)=>{
 out.push(`insert into classes(id,name,level,blurb,sort) values(${q(c.id)},${q(c.name)},${q(c.level)},${q(c.blurb)},${ci}) on conflict(id) do update set name=excluded.name,level=excluded.level,blurb=excluded.blurb,sort=excluded.sort;`)
 c.subjects.forEach((s,si)=>{
  out.push(`insert into subjects(id,class_id,name,stream,sort) values(${q(s.id)},${q(c.id)},${q(s.name)},${s.stream?q(s.stream):'null'},${si}) on conflict(id) do update set name=excluded.name,stream=excluded.stream,sort=excluded.sort;`)
  s.chapters.forEach((ch,hi)=>{
   out.push(`insert into chapters(id,subject_id,name,sort) values(${q(ch.id)},${q(s.id)},${q(ch.name)},${hi}) on conflict(id) do update set name=excluded.name,sort=excluded.sort;`)
   ch.topics.forEach((t,ti)=>out.push(`insert into topics(id,chapter_id,name,description,subtopics,sort) values(${q(t.id)},${q(ch.id)},${q(t.name)},${q(t.description)},${q(JSON.stringify(t.subtopics))}::jsonb,${ti}) on conflict(id) do update set name=excluded.name,description=excluded.description,subtopics=excluded.subtopics,sort=excluded.sort;`))})})})
Object.entries(topicContent).forEach(([id,content])=>out.push(`insert into topic_content(topic_id,language,content) values(${q(id)},'English',${q(JSON.stringify(content))}::jsonb) on conflict(topic_id,language) do update set content=excluded.content;`))
out.push('commit;')
writeFileSync(new URL('../supabase/seed.sql',import.meta.url),out.join('\n')+'\n')
console.log(`Wrote supabase/seed.sql (${out.length} statements)`)
